version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lifu_butler
      - SECRET_KEY=your_secret_key_here
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - lifu-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - lifu-network

  # 数据库服务
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lifu_butler
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lifu-network

  # Nginx服务
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - lifu-network

networks:
  lifu-network:
    driver: bridge

volumes:
  postgres_data: 